spring.application.name=bff-web
server.port=8444

# HTTPS / TLS con Keystore PKCS12
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=blanquito123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz_cert

# Core Bancario URL
bank.core.url=http://localhost:8080/api/core

# JWT Clientes Web
jwt.secret=mi-clave-secreta-bancoxyz-2026-para-jwt-1234567890-super-segura
jwt.expiration=3600000

# Service Token (Delegado hacia Core)
jwt.service-secret=clave-compartida-bff-bancoxyz-service-token-2026-1234567890
jwt.service-expiration=300000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
