server.port=8443
spring.application.name=bff-movil

# HTTPS / TLS con Keystore PKCS12
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=blanquito123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bancoxyz_cert

# URL logica de Core Bancario descubierta via Eureka (@LoadBalanced)
bank.core.url=http://core-service/api/core

# JWT Clientes Movil y Service Tokens
jwt.secret=mi-clave-secreta-bancoxyz-2026-para-jwt-1234567890-super-segura
jwt.expiration=3600000
jwt.service-secret=clave-compartida-bff-bancoxyz-service-token-2026-1234567890
jwt.service-expiration=300000

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreaker.enabled=true

# Eureka
eureka.client.service-url.defaultZone=http://eureka:eureka2026@localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.healthcheck.enabled=true

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.coreServiceCB.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.coreServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.coreServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.coreServiceCB.waitDurationInOpenState=10000
resilience4j.circuitbreaker.instances.coreServiceCB.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.coreServiceCB.automaticTransitionFromOpenToHalfOpenEnabled=true

# Resilience4j Retry
resilience4j.retry.instances.coreServiceCB.maxAttempts=3
resilience4j.retry.instances.coreServiceCB.waitDuration=1000ms
resilience4j.retry.instances.coreServiceCB.enableExponentialBackoff=false
