spring.application.name=core-service
server.port=8080

# Clave compartida para validación de Service Tokens emitidos por los BFFs
service-token.secret=clave-compartida-bff-bancoxyz-service-token-2026-1234567890

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
